export enum StatusCode {
    INVALID_PARAMETER = 422,
    ACCESS_DENIED = 403,
    SUCCESSFULL = 200
}

export enum ResponseType {
    INVALID_PARAMETER = 'INVALID_PARAMETER',
    ACCESS_DENIED = 'ACCESS_DENIED',
    SUCCESSFULL = 'SUCCESSFULL'
}